// Insights articles — recovered from the original site and corrected per client instruction:
// no unsupported statistics or monetary figures, no "studies show" without a named source,
// no emojis, no NHS Trust / customer-experience claims. TMMS references use approved wording.

export const INSIGHTS = [
    {
        slug: "what-is-a-cmms",
        tag: "CMMS basics",
        title: "What is a CMMS?",
        dek: "A plain-English guide to Computerised Maintenance Management Systems — what they do, who uses one, and how they change the way maintenance is run.",
        description:
            "A CMMS (Computerised Maintenance Management System) helps operations teams plan, track and manage maintenance in one place. What it is, what it does and who it is for.",
        date: "May 2026",
        dateIso: "2026-05-01",
        readingTime: "5 min read",
        related: "reactive-vs-preventive-maintenance",
        blocks: [
            { t: "p", text: "If you are managing maintenance across a facility, a fleet or multiple sites, you have probably heard the term **CMMS**. But what does it actually mean, and why does it matter for your operation?" },
            { t: "p", text: "Let us break it down simply, then go a little deeper for anyone who wants the full picture." },
            { t: "h2", text: "The simple answer" },
            { t: "p", text: "**CMMS** stands for **Computerised Maintenance Management System**. It is software that helps you plan, track and manage maintenance activity in one place, instead of spreadsheets, paper records and phone calls." },
            { t: "callout", text: "**Think of it this way:** a CMMS is to maintenance what an accounting system is to finance. It brings everything into one place, makes it visible and keeps it organised." },
            { t: "h2", text: "What does a CMMS actually do?" },
            { t: "p", text: "At its core, a CMMS gives you control over a few key areas:" },
            {
                t: "list",
                items: [
                    "**Asset management** — a register of every piece of equipment, with its location, age, service history and documentation.",
                    "**Planned preventive maintenance (PPM)** — scheduled tasks with due dates, so routine work is not missed.",
                    "**Work order management** — raise, assign, track and close jobs digitally, rather than on paper.",
                    "**Parts and inventory** — a view of the spares you hold, where they are and when to reorder.",
                    "**Compliance tracking** — certificates and inspections recorded, with expiry reminders.",
                    "**Reporting and insight** — clear reports covering cost, downtime, performance and trends.",
                ],
            },
            { t: "h2", text: "Who uses a CMMS?" },
            { t: "p", text: "A CMMS is used across many sectors wherever assets and maintenance matter, including:" },
            {
                t: "list",
                items: [
                    "**Manufacturing and industrial sites** — protecting uptime and equipment reliability.",
                    "**Warehousing and logistics** — maintaining handling equipment, conveyors and depot assets.",
                    "**Commercial and industrial facilities** — coordinating planned work and contractors across a building or portfolio.",
                    "**Hotels and hospitality** — keeping plant, guest-facing equipment and multi-site assets in good order.",
                    "**Healthcare estates** — managing critical estates equipment and compliance-led maintenance.",
                ],
            },
            { t: "h2", text: "Reactive vs preventive — the core problem a CMMS solves" },
            { t: "p", text: "Many maintenance teams operate **reactively**: they fix equipment when it breaks. That tends to be more disruptive, harder to plan around and more expensive than planned work, particularly in regulated environments." },
            { t: "p", text: "A CMMS supports a shift towards **preventive maintenance** — servicing assets on a schedule, before they fail — so more work is planned, recorded and visible rather than reactive." },
            { t: "callout", text: "**The result:** less firefighting, better planning and a clearer record of what has been done, and what is due next." },
            { t: "h2", text: "Do you need one?" },
            { t: "p", text: "If you are managing a growing number of assets, several engineers or ongoing compliance obligations on spreadsheets or paper, a CMMS is worth serious consideration." },
            { t: "p", text: "The question is usually not whether a CMMS would help, but which approach is right for your operation and how to introduce it so the team actually uses it." },
            { t: "p", text: "That is the kind of maintenance thinking we care about at **Nachi Eng Ltd** — and the thinking behind [TMMS](/tmms), the maintenance management system we are developing." },
        ],
    },
    {
        slug: "reactive-vs-preventive-maintenance",
        tag: "Maintenance strategy",
        title: "The 2am Phone Call That's Costing Your Facility a Fortune",
        dek: "Many facilities teams get trapped in reactive maintenance — always fixing, never planning. Here is why it happens, and how a CMMS helps break the cycle.",
        description:
            "Why so many facilities teams stay stuck in reactive maintenance, what it really costs in disruption and risk, and how a CMMS helps shift to planned, preventive work.",
        date: "May 2026",
        dateIso: "2026-05-01",
        readingTime: "6 min read",
        related: "what-is-a-cmms",
        blocks: [
            { t: "p", text: "It often starts the same way." },
            { t: "p", text: "A phone call in the middle of the night. A piece of critical equipment has failed. The on-call engineer is half asleep and an hour away. Production has stopped, or a building full of people has no heating." },
            { t: "p", text: "And somewhere in the chaos, someone asks the question nobody wants to answer:" },
            { t: "quote", text: "Why didn't we see this coming?", cite: "— every estates manager, at least once" },
            { t: "p", text: "The honest answer is usually that the warning signs were there. They just were not acted on." },
            { t: "h2", text: "The reactive maintenance trap" },
            { t: "p", text: "Many facilities teams are stuck in what I think of as the **reactive maintenance trap**. Something breaks, you fix it. Something else breaks, you fix that too. The cycle rarely ends, and neither do the costs and disruption that come with it." },
            { t: "p", text: "Reactive work tends to be more expensive and more disruptive than planned maintenance: it happens out of hours, under pressure, often with parts ordered in a hurry and knock-on effects on operations and compliance." },
            { t: "p", text: "And yet, when budgets are reviewed, preventive maintenance is often the first thing cut. It feels optional, until it isn't." },
            { t: "h2", text: "Reactive vs preventive: the practical difference" },
            { t: "p", text: "Set the two approaches side by side and the difference is clear, even without putting a single figure on it." },
            {
                t: "table",
                head: ["", "Reactive (emergency)", "Preventive (planned)"],
                rows: [
                    ["Timing", "Out of hours, under pressure", "Scheduled and prepared"],
                    ["Parts", "Ordered in a panic", "Budgeted, often in stock"],
                    ["Knock-on impact", "Lost production, complaints, compliance risk", "Minimal, planned around operations"],
                    ["Audit readiness", "Scrambling for paperwork", "Documentation ready to hand"],
                ],
            },
            { t: "p", text: "Repeat an emergency call-out on the same asset a few times a year, then multiply that across a facility with dozens or hundreds of assets, and the scale of the problem becomes clear." },
            { t: "h2", text: "Why most teams stay reactive" },
            { t: "p", text: "If preventive maintenance is so clearly better, why do so many teams still operate reactively? In practice, it usually comes down to three things:" },
            {
                t: "list",
                items: [
                    "**Reactive work feels urgent, preventive work feels optional.** Until something fails in the middle of winter, it is always \u201cnext quarter\u201d.",
                    "**Without the right system, planned maintenance is genuinely hard to manage.** Spreadsheets, paper and memory are no match for a facility with hundreds of assets.",
                    "**Nobody gets praised for the breakdown that didn't happen.** Culture tends to reward firefighting, not planning.",
                ],
            },
            { t: "callout", text: "**The result:** teams spend enormous energy reacting to problems that were largely predictable, while the information needed to prevent them sits in a filing cabinet, or in someone's head." },
            { t: "h2", text: "The CMMS difference" },
            { t: "p", text: "A **Computerised Maintenance Management System (CMMS)** helps break the reactive cycle — not by adding more work, but by making planned maintenance the path of least resistance." },
            { t: "p", text: "Instead of waiting for things to fail, a CMMS schedules maintenance based on manufacturer guidance, usage and compliance requirements. Every asset gets a schedule. Every job leaves a record. Every compliance document is stored and easy to retrieve." },
            { t: "p", text: "The benefit is not only fewer breakdowns, but clearer operational visibility:" },
            {
                t: "list",
                items: [
                    "You can see the condition of critical equipment at any time.",
                    "You can plan and forecast maintenance across the year.",
                    "You walk into a compliance audit prepared, rather than scrambling.",
                    "Engineers spend less time firefighting and more time managing.",
                    "Managers get a live picture instead of a reactive phone call.",
                ],
            },
            { t: "h2", text: "From chaos to control" },
            { t: "p", text: "Teams that make this shift tend to change how the whole organisation thinks about maintenance. It stops being seen purely as a cost and starts being understood as a function that protects operations, supports compliance and extends the life of expensive assets." },
            { t: "p", text: "At **Nachi Eng Ltd**, this thinking comes from hands-on industrial maintenance experience across manufacturing and commercial environments. It is also the thinking behind [TMMS](/tmms), a maintenance management system we are developing to support structured maintenance workflows across manufacturing, logistics, commercial facilities, hospitality and, in future, healthcare estates. TMMS is not presented as a released product, and no customer deployment is claimed." },
            { t: "divider" },
            { t: "p", text: "The question is not really whether your facility can afford planned maintenance." },
            { t: "p", text: "**It is whether you can afford to keep doing it the old way.**" },
        ],
    },
];

export const getArticle = (slug) => INSIGHTS.find((a) => a.slug === slug);
